CREATE TABLE IF NOT EXISTS items (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(64) CHARACTER SET UTF8 NOT NULL,
    sensitivity BOOLEAN
);
