CREATE TABLE IF NOT EXISTS recipes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(64) CHARACTER SET UTF8 NOT NULL,
    source VARCHAR(64) CHARACTER SET UTF8,
    source_url VARCHAR(128) CHARACTER SET UTF8
);
