CREATE TABLE IF NOT EXISTS recipes (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(64) CHARACTER SET UTF8 NOT NULL,
    source VARCHAR(64) CHARACTER SET UTF8,
    source_url VARCHAR(128) CHARACTER SET UTF8
);
