CREATE TABLE IF NOT EXISTS user_items( id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
        user_id BIGINT NOT NULL ,
        item_id BIGINT NOT NULL  ,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE ,
        FOREIGN KEY (item_id) REFERENCES items(id) ON UPDATE CASCADE ON DELETE CASCADE );